### ISSUE TITLE
Core check fails after installing the app

### ISSUE THREAD

**Issue by solracsf** [jgraph/drawio-nextcloud#26]
```
# occ integrity:check-core

  - INVALID_HASH:
    - core/js/mimetypelist.js:
      - expected: 94195a260a005dac543c3f6aa504f1b28e0078297fe94a4f52f012c16c109f0323eecc9f767d6949f860dfe454625fcaf1dc56f87bb8350975d8f006bbbdf14a
      - current: 7261357dcb345c083894f3905c321b735972045aafa6420ecd748d5a60cd8036a9d6a21e6711eae5a1bccfb53909497e955b2cde70fa412eff184fcd4772a832

  - EXTRA_FILE:
    - core/img/filetypes/drawio.svg:
      - expected:
      - current: 92e0974cf869bf8ab969c3442dc2b80d55fde36441d22924db74916a06b407520aa2a9dc39336f9157195ebede697ffac0e639360879255ab91932d406e1897d
    - core/img/filetypes/dwb.svg:
      - expected:
      - current: 43731dd5f17a048112ea5109b40b02ec019b3ee2324385a0f448e3bd2264cb13dc160ab018d893f92f8e2f168fd09009b51578c8c6b97a02a1617c67ac087701
```
